account/urls.py
from django.urls import path, include
from .views import home, login, register, add_instagram
app_name='account'
urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('add-instagram/', add_instagram, name='add-instagram'),


]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='account'))

]

account/models.py
from django.db import models
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

class User(AbstractUser):
    email = models.EmailField(_('email address'), blank=True, unique=True)
    is_active = True
    followers = models.IntegerField(blank=True, null=True, default=0)
    following = models.IntegerField(blank=True, null=True, default=0)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

account/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import password_validation
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

User = get_user_model()

class RegistrationForm(UserCreationForm):

    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'New Password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Confirm Password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = (
            'username',
            'email',
        )

        widgets = {

            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'E-mail'}),
        }

class LoginForm(forms.Form):
    email = forms.EmailField(max_length=127, widget=forms.EmailInput(attrs={'class' : 'form-control', 'placeholder': 'E-mail'}))
    password = forms.CharField(max_length=127, widget=forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder': 'Password'}))

account/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from . forms import RegistrationForm, LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login as django_login, logout as django_logout
from django.contrib.auth.decorators import login_required
from selenium import webdriver
from time import sleep
from selenium.webdriver.common.by import By
from core.celery import debug_task
# Create your views here.
from .tasks import print_something

User = get_user_model()
@login_required
def home(request):
    # print_something().delay()
    current_user = request.user
    following = current_user.following
    # print(following)
    followers = current_user.followers
    context = {
        'follower': followers,
        'following': following
    }

    return render(request, 'index.html', context)


def add_instagram(request):
    current_user = User.objects.get(email__exact=request.user.email)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        browser = webdriver.Chrome()

        browser.implicitly_wait(1)

        browser.get('https://www.instagram.com/')

        sleep(1)

        username_input = browser.find_element(By.CSS_SELECTOR,"input[name='username']" )
        password_input = browser.find_element(By.CSS_SELECTOR,"input[name='password']" )

        username_input.send_keys(username)
        password_input.send_keys(password)


        login_button = browser.find_element(By.XPATH , "//button[@type='submit']")
        login_button.click()
        sleep(10)
        browser.get(f'https://www.instagram.com/{username}')
        

        # browser.find_element(By.XPATH,"//*[@id='mount_0_0_xl']/div/div/div[2]/div/div/div/div[1]/div[1]/div[2]/section/main/div/div/div/div/div").click()
        # print('not now clikced')
        # browser.find_element_by_xpath("//button[contains(text(),'Not Now')]").click()


        
        follower_count = int(browser.find_element(By.XPATH,".//*[contains(text(), 'followers')]/span").text)
        following_count = int(browser.find_element(By.XPATH, ".//*[contains(text(), 'following')]/span").text)
        current_user.followers = follower_count
        current_user.following = following_count
        current_user.save()
        
        print(follower_count, '-----------------------', following_count)



        # print('fiolll;', follower_count)
        # sleep(5)

        browser.close()
        return redirect(reverse_lazy('account:home'))
    # update_instagram_counts.apply_async(args=[current_user.email], countdown=1)





    return render(request, 'instagram.html')

# def login(request):
#     return render(request, 'login.html')

# def register(request):
#     return render(request, 'register.html')

def login(request):
    form = LoginForm()
    if request.method =='POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(username=email, password=password)
            if user:
                django_login(request, user)
                print('looged in')
                messages.success(request, 'Siz ugurla login oldunuz')
                return redirect(reverse_lazy('account:home'))
            else:
                messages.success(request, 'Siz login ola bilmediniz')
    context = {
        'form': form,
    }
    return render(request, 'login.html', context)


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(data =request.POST, files = request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password = form.cleaned_data.get('password1')
            user.is_active = False
            user.save()
            site_address = request.is_secure() and "https://" or "http://" + request.META['HTTP_HOST']  # https
            messages.success(request, 'Siz ugurla qeydiyyatdan kecdiniz')
            return redirect(reverse_lazy('account:login'))
    context = {
        'form' : form
    }
    return render(request, 'register.html', context)

account/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>Hello {{request.user.username}} currently you have {{follower}} follower and you follow {{ following }} accounts
    </h1>
    <div>
        <h4>
            <div
                style="height: 40px; background-color: #0088cc; width: 105px; justify-content: center; align-items: center;text-align: center;">
                <a style="color: aliceblue; ;" href="{% url 'account:add-instagram' %}">Connect instagram</a>
            </div>
        </h4>
    </div>
</body>

</html>

account/templates/instagram.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>

<div class="container-fluid">
    <div class="row my-5 mx-5">

        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input name="username" type="" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="Enter username">
                <small id="emailHelp" class="form-text text-muted">
                </small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input name="password" type="password" class="form-control" id="exampleInputPassword1"
                    placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
</div>

account/templates/login.html
<!-- Start of Main -->
{% load static %}

<head>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo1.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo2.min.css' %}">


</head>
<main class="main login-page">
    <!-- Start of Page Header -->
    <div class="page-header">
        <div class="container">
            <h1 class="page-title mb-0">Login Page</h1>
        </div>
    </div>
    <!-- End of Page Header -->

    <!-- Start of Breadcrumb -->
    <nav class="breadcrumb-nav">

    </nav>
    <!-- End of Breadcrumb -->
    <div class="page-content">
        <div class="container">
            <div class="login-popup">
                <div class="tab tab-nav-boxed tab-nav-center tab-nav-underline">
                    <ul class="nav nav-tabs text-uppercase" role="tablist">
                        <li class="nav-item">
                            <a href="#sign-in" class="nav-link active">Sign In </a>
                        </li>

                    </ul>
                    <div class="tab-content">
                        <form action="" method="post" class="bg-light p-5 contact-form">
                            {% csrf_token %}
                            {% for error in form.non_field_errors %}
                            {{error}}
                            {% endfor %}
                            <div class="tab-pane active" id="sign-in">
                                {% for field in form %}
                                <div class="form-group">
                                    {{ field }}
                                    {% for error in field.errors %}
                                    <p>{{error}}</p>
                                    {% endfor %}
                                </div>
                                {% endfor %}
                                <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                            </div>
                            <div
                                style="height: 30px; background-color: #0088cc; width: 105px; justify-content: center; align-items: center;text-align: center;">
                                <a style="color: aliceblue; ;" href="{% url 'account:register' %}">Register</a>
                            </div>

                        </form>

                    </div>
                    <!-- {% comment %} <p class="text-center">Sign in with social account</p>
                    <div class="social-icons social-icon-border-color d-flex justify-content-center">
                        <a href="{% url 'social:begin' 'facebook' %}"
                            class="social-icon social-facebook w-icon-facebook"></a>
                        <a href="#" class="social-icon social-twitter w-icon-twitter"></a>
                        <a href="{% url 'social:begin' 'google-oauth2' %}"
                            class="social-icon social-google fab fa-google"></a>
                    </div> {% endcomment %} -->
                </div>
            </div>
        </div>
    </div>
</main>
<!-- End of Main -->

account/templates/register.html
<!-- Start of Main -->
<!-- Start of Main -->
{% load static %}

<head>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo1.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo2.min.css' %}">


</head>
<main class="main login-page">
    <!-- Start of Page Header -->
    <div class="page-header">
        <div class="container">
            <h1 class="page-title mb-0">Register Psge</h1>
        </div>
    </div>
    <!-- End of Page Header -->

    <!-- Start of Breadcrumb -->
    <nav class="breadcrumb-nav">
        <div class="container">

        </div>
    </nav>
    <!-- End of Breadcrumb -->
    <div class="page-content">
        <div class="container">
            <div class="login-popup">
                <div class="tab tab-nav-boxed tab-nav-center tab-nav-underline">
                    <ul class="nav nav-tabs text-uppercase" role="tablist">
                        <li class="nav-item">
                            <a href="#sign-up" class="nav-link"> Sign Up</a>
                        </li>
                    </ul>
                    <form action="" method="post" enctype='multipart/form-data' class="bg-light p-5 contact-form">
                        {% csrf_token %}
                        <div class="tab-pane" id="sign-up">
                            {% for field in form %}
                            <div class="form-group">
                                {{ field }}
                                {% for error in field.errors %}
                                <li class="alert-danger alert">{{ error }}</li>
                                {% endfor %}
                            </div>
                            {% endfor %}
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>
                </div>
                <div
                    style="height: 30px; background-color: #0088cc; width: 105px; justify-content: center; align-items: center;text-align: center;">
                    <a style="color: aliceblue; ;" href="{% url 'account:login' %}">Login</a>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>
<!-- End of Main -->